/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/admin/tags/": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            name: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              name: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
  };
  "/api/admin/tags/{tagId}/": {
    delete: {
      parameters: {
        path: {
          tagId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          tagId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            name: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              id: string;
              name: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
  };
  "/api/admin/users/": {
    get: {
      parameters: {
        query?: {
          offset?: number;
          limit?: number;
          search?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: ({
                  subId: string;
                  email: string;
                  isActive: boolean;
                  id: string;
                  name: string | null;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                  isPending: boolean;
                  /** @enum {string} */
                  role: "admin" | "user";
                })[];
              meta: {
                offset?: number;
                limit?: number;
                total?: number;
                totalPages?: number;
                page?: number;
              };
            };
          };
        };
      };
    };
  };
  "/api/admin/users/{userId}/disable-user/": {
    post: {
      parameters: {
        path: {
          userId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
  };
  "/api/admin/users/{userId}/enable-user/": {
    post: {
      parameters: {
        path: {
          userId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
  };
  "/api/admin/users/{userId}/resend-invite/": {
    post: {
      parameters: {
        path: {
          userId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            redirectUrl: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
  };
  "/api/admin/users/invite-user/": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            redirectUrl: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
  };
  "/api/auth/accept-invite/": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
            name: string;
            signature: string;
            expireAt: number;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/auth/signup/": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
            name: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/posts/": {
    get: {
      parameters: {
        query?: {
          offset?: number;
          limit?: number;
          search?: string;
          sortBy?: "createdAt" | "title" | "commentsCount";
          sortOrder?: "asc" | "desc";
          numericFilters?: string[] | string;
          tagIds?: string[] | string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: ({
                  /** Format: uuid */
                  id: string;
                  title: string;
                  description?: string | null;
                  readingTime: number;
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: uuid */
                  userId: string;
                  user: {
                    subId: string;
                    email: string;
                    isActive?: boolean;
                    id: string;
                    name: string | null;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                    isPending: boolean;
                    /** @enum {string} */
                    role: "admin" | "user";
                  };
                  tags: {
                      id: string;
                      name: string;
                      /** Format: date-time */
                      createdAt: string;
                      /** Format: date-time */
                      updatedAt: string;
                    }[];
                  commentsCount: number;
                })[];
              meta: {
                offset?: number;
                limit?: number;
                total?: number;
                totalPages?: number;
                page?: number;
              };
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            title: string;
            description?: string;
            tagIds?: string[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              title: string;
              description?: string | null;
              readingTime: number;
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: uuid */
              userId: string;
              user: {
                subId: string;
                email: string;
                isActive?: boolean;
                id: string;
                name: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                isPending: boolean;
                /** @enum {string} */
                role: "admin" | "user";
              };
              tags: {
                  id: string;
                  name: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                }[];
              comments: ({
                  /** Format: uuid */
                  id: string;
                  text: string;
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: uuid */
                  postId: string;
                  /** Format: uuid */
                  userId: string;
                  user: {
                    subId: string;
                    email: string;
                    isActive?: boolean;
                    id: string;
                    name: string | null;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                    isPending: boolean;
                    /** @enum {string} */
                    role: "admin" | "user";
                  };
                })[];
            };
          };
        };
      };
    };
  };
  "/api/posts/{postId}/": {
    get: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              title: string;
              description?: string | null;
              readingTime: number;
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: uuid */
              userId: string;
              user: {
                subId: string;
                email: string;
                isActive?: boolean;
                id: string;
                name: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                isPending: boolean;
                /** @enum {string} */
                role: "admin" | "user";
              };
              tags: {
                  id: string;
                  name: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                }[];
              comments: ({
                  /** Format: uuid */
                  id: string;
                  text: string;
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: uuid */
                  postId: string;
                  /** Format: uuid */
                  userId: string;
                  user: {
                    subId: string;
                    email: string;
                    isActive?: boolean;
                    id: string;
                    name: string | null;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                    isPending: boolean;
                    /** @enum {string} */
                    role: "admin" | "user";
                  };
                })[];
            };
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          postId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            title: string;
            description?: string;
            tagIds?: string[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              title: string;
              description?: string | null;
              readingTime: number;
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: uuid */
              userId: string;
              user: {
                subId: string;
                email: string;
                isActive?: boolean;
                id: string;
                name: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                isPending: boolean;
                /** @enum {string} */
                role: "admin" | "user";
              };
              tags: {
                  id: string;
                  name: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                }[];
              comments: ({
                  /** Format: uuid */
                  id: string;
                  text: string;
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: uuid */
                  postId: string;
                  /** Format: uuid */
                  userId: string;
                  user: {
                    subId: string;
                    email: string;
                    isActive?: boolean;
                    id: string;
                    name: string | null;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    updatedAt: string;
                    isPending: boolean;
                    /** @enum {string} */
                    role: "admin" | "user";
                  };
                })[];
            };
          };
        };
      };
    };
  };
  "/api/posts/{postId}/comments/": {
    get: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": ({
                /** Format: uuid */
                id: string;
                text: string;
                /** Format: date-time */
                updatedAt: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: uuid */
                postId: string;
                /** Format: uuid */
                userId: string;
                user: {
                  subId: string;
                  email: string;
                  isActive?: boolean;
                  id: string;
                  name: string | null;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: date-time */
                  updatedAt: string;
                  isPending: boolean;
                  /** @enum {string} */
                  role: "admin" | "user";
                };
              })[];
          };
        };
      };
    };
    post: {
      parameters: {
        path: {
          postId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            text: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              text: string;
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: uuid */
              postId: string;
              /** Format: uuid */
              userId: string;
              user: {
                subId: string;
                email: string;
                isActive?: boolean;
                id: string;
                name: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                isPending: boolean;
                /** @enum {string} */
                role: "admin" | "user";
              };
            };
          };
        };
      };
    };
  };
  "/api/posts/{postId}/comments/{commentId}/": {
    patch: {
      parameters: {
        path: {
          postId: string;
          commentId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            text?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              text: string;
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: uuid */
              postId: string;
              /** Format: uuid */
              userId: string;
              user: {
                subId: string;
                email: string;
                isActive?: boolean;
                id: string;
                name: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
                isPending: boolean;
                /** @enum {string} */
                role: "admin" | "user";
              };
            };
          };
        };
      };
    };
  };
  "/api/posts/{postId}/comments/{commentId}/delete-hard/": {
    delete: {
      parameters: {
        path: {
          commentId: string;
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
  };
  "/api/posts/{postId}/comments/{commentId}/delete-soft/": {
    delete: {
      parameters: {
        path: {
          commentId: string;
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
  };
  "/api/posts/{postId}/delete-hard/": {
    delete: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/posts/{postId}/delete-soft/": {
    delete: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/posts/{postId}/edit-tags/": {
    post: {
      parameters: {
        path: {
          postId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            tagIds: string[];
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
                id: string;
                name: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              }[];
          };
        };
      };
    };
  };
  "/api/tags/": {
    get: {
      parameters: {
        query?: {
          search?: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
                id: string;
                name: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                updatedAt: string;
              }[];
          };
        };
      };
    };
  };
  "/api/user-profile/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              subId: string;
              email: string;
              isActive?: boolean;
              id: string;
              name: string | null;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
              isPending: boolean;
              /** @enum {string} */
              role: "admin" | "user";
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description - GENERAL_ERROR -> 1000
     * - USER_ALREADY_EXISTS -> 1001
     * - PERMISSION_DENIED -> 1002
     * - INVALID_SIGNATURE -> 1003
     * - INVITE_EXPIRED -> 1004
     * - USER_ALREADY_ACTIVATED -> 1005
     * - USER_NOT_FOUND -> 1006
     * - USER_ALREADY_INVITED -> 1007
     * @enum {integer}
     */
    ErrorCodes: 1000 | 1001 | 1002 | 1003 | 1004 | 1005 | 1006 | 1007;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
