/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/health": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/auth/signup/": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            /** Format: email */
            email: string;
            password: string;
            name: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
  "/api/posts/": {
    get: {
      parameters: {
        query?: {
          offset?: number;
          limit?: number;
          search?: string;
          sortBy?: "createdAt" | "title" | "commentsCount";
          sortOrder?: "asc" | "desc";
          numericFilters?: string[] | string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              data: ({
                  /** Format: uuid */
                  id: string;
                  title: string;
                  description?: string | null;
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: date-time */
                  createdAt: string;
                  commentsCount: number;
                  readingTime: number;
                })[];
              meta: {
                offset?: number;
                limit?: number;
                total?: number;
                totalPages?: number;
                page?: number;
              };
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "application/json": {
            title: string;
            description?: string | null;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              title: string;
              description?: string | null;
              readingTime: number;
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              comments: {
                  /** Format: uuid */
                  id: string;
                  text: string;
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: uuid */
                  postId: string;
                }[];
            };
          };
        };
      };
    };
  };
  "/api/posts/{postId}/": {
    get: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              title: string;
              description?: string | null;
              readingTime: number;
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              comments: {
                  /** Format: uuid */
                  id: string;
                  text: string;
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: uuid */
                  postId: string;
                }[];
            };
          };
        };
      };
    };
    delete: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          postId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            title?: string;
            description?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              title: string;
              description?: string | null;
              readingTime: number;
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              comments: {
                  /** Format: uuid */
                  id: string;
                  text: string;
                  /** Format: date-time */
                  updatedAt: string;
                  /** Format: date-time */
                  createdAt: string;
                  /** Format: uuid */
                  postId: string;
                }[];
            };
          };
        };
      };
    };
  };
  "/api/posts/{postId}/comments/": {
    get: {
      parameters: {
        path: {
          postId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
                /** Format: uuid */
                id: string;
                text: string;
                /** Format: date-time */
                updatedAt: string;
                /** Format: date-time */
                createdAt: string;
                /** Format: uuid */
                postId: string;
              }[];
          };
        };
      };
    };
    post: {
      parameters: {
        path: {
          postId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            text: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              text: string;
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: uuid */
              postId: string;
            };
          };
        };
      };
    };
  };
  "/api/posts/{postId}/comments/{commentId}/": {
    delete: {
      parameters: {
        path: {
          postId: string;
          commentId: string;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
    patch: {
      parameters: {
        path: {
          postId: string;
          commentId: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": {
            text?: string;
          };
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              /** Format: uuid */
              id: string;
              text: string;
              /** Format: date-time */
              updatedAt: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: uuid */
              postId: string;
            };
          };
        };
      };
    };
  };
  "/api/user-profile/": {
    get: {
      responses: {
        /** @description Default Response */
        200: {
          content: {
            "application/json": {
              subId: string;
              email: string;
              id: string;
              name: string;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description - GENERAL_ERROR -> 1000
     * @enum {integer}
     */
    ErrorCodes: 1000;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
